apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docker-image-demo
  namespace: argocd
spec:
  project: docker-apps  # 🔗 Зв'язок із AppProject
  source:
    repoURL: git@github.com:StanislavYermolenko/gitops-config.git
    targetRevision: master
    path: apps/docker-image-demo
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
